#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper dir_to_symlink /usr/share/themes/Kali-Light/gtk-3.0/assets ../../Kali-Dark/gtk-3.0/assets 2021.2.2\~ -- "$@"
# End automatically added section
